### ISSUE TITLE
xkb Custom Keyboard Layout Not Working

### ISSUE THREAD

**Issue by frosDfurret** [rgvxsthi/Braswell-EDGAR-Linux-Fixes#1]
Using a Dell Chromebook 11 3180, sound fixes worked great but xkb replacement results in no change. Already tried clearing xkb cache, still no change. Running Ubuntu 20.04, looking through the "Region and Language" section of settings.

**Comment by rgvxsthi** [comment]
Hi @frosDfurret ,

Can you please try the following steps (all credits go [to this post on Reddit](https://www.reddit.com/r/GalliumOS/comments/nx25tq/install_chromebook_keyboard_on_ubuntu_and_debian/))

1. Open a terminal and type in the following command:
`wget https://apt.galliumos.org/pool/main/x/xkeyboard-config/xkb-data_2.23.1-1ubuntu1-galliumos1_all.deb`
2. Once downloaded, install the package:
`sudo dpkg -i xkb-data_2.23.1-1ubuntu1-galliumos1_all.deb`
3. Go to your keyboard settings, layout, Keyboard model, and choose which chromebook model you want. If you're not sure check the [GalliumOS Wiki](https://wiki.galliumos.org/Media_keys_and_default_keybindings).

EDIT:
Just tested this on a brand new installation of Xubuntu 20.04, working well for me. [Screenshot](https://prnt.sc/1aypq3r)
Will update the original instructions with the same.
